name: This is the name in top of the .yaml file
on:
    issues:
        types: [opened, reopened]
jobs:
    job-1:
        runs-on: ubuntu-latest #uses GitHub's hosted Ubuntu runner 
        permissions:
            contents: read
            issues: write
        steps:
            - name: step1-Install JQ
              run: |
                sudo apt-get update
                sudo apt-get install -y jq curl gh
            - name: step2-Call Zoo first time
              id: zoo
              run: |
                echo "Hello, Zoo!"
              
                ## ---------- Get the issue text ---------- 
                # Get the issue description
                ISSUE_DESCRIPTION=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
                echo "ISSUE_DESCRIPTION: $ISSUE_DESCRIPTION"

                # Get the issue title
                ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
                echo "ISSUE_TITLE: $ISSUE_TITLE"
                ## __________ Get the issue text __________

              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
