name: ✨ Criticize new issues
on:
  issues:
    types: [opened, reopened]

jobs:
  call-zoo:
    runs-on: ubuntu-latest #<-- OPS!! Må endres til innovation-k8s
    permissions:
      contents: read
      issues: write
    steps:
      - name: Install JQ
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl gh

      - name: step0-defines-variables
        run: |
          echo "checkpoint 240915104726"
          # Set the variables
          echo "STRING1=hei og hallo"
          echo "NUMBER1=123" 
          echo "STRING1 = $STRING1" >> $GITHUB_ENV
          echo "NUMBER1 = $NUMBER1" >> $GITHUB_ENV
          echo "checkpoint 240915104732"

      - name: step1-refere-to-variables
        run: |
          echo "checkpoint 240915104525"
          echo "STRING1: $STRING1"
          echo "NUMBER1: $NUMBER1"
          echo "checkpoint 240915104530"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
