name: ✨ Criticize new issues
on:
    issues:
        types: [opened, reopened]
jobs:
    call-zoo:
        runs-on: ubuntu-latest #uses GitHub's hosted Ubuntu runner 
        permissions:
            contents: read
            issues: write
        steps:
            - name: Install JQ
              run: |
                sudo apt-get update
                sudo apt-get install -y jq curl gh
                      
            - name: Call Zoo first time
              id: zoo
              run: |
                MESSAGE="Hello, Zoo!"
                echo "The message is: $MESSAGE"
              
                # ---------- Paste answer to issue ----------
                # Write the message as a comment on the issue
                gh issue --repo ${{ github.repository }} comment ${{ github.event.issue.number }} -b "$MESSAGE"
                ## __________ Paste answer to issue __________
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
