name: ✨ Criticize new issues
on:
    issues:
        types: [opened, reopened]

jobs:
    call-zoo:
        runs-on: ubuntu-latest #<-- OPS!! Må endres til innovation-k8s
        permissions:
            contents: read
            issues: write
        steps:
            - name: Install JQ
              run: |
                sudo apt-get update
                sudo apt-get install -y jq curl gh
            - name: Get Issue Description
              run: |
                # Get the issue description
                ISSUE_DESCRIPTION=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
                echo "ISSUE_DESCRIPTION: $ISSUE_DESCRIPTION"
                echo "cp 2409160807"

                # Get the issue title
                ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
                echo "ISSUE_TITLE: $ISSUE_TITLE"
                echo "cp 2409160806"

                # Set outputs
                echo "ISSUE_TITLE=$ISSUE_TITLE" >> $GITHUB_ENV
                echo "ISSUE_DESCRIPTION=$ISSUE_DESCRIPTION" >> $GITHUB_ENV    
                echo "cp 2409160821"

            - name: Rate Issue Description
              id: rate_issue
              run: |

                # Define the prompt using printf
                PROMPT=$(printf '%s\n' \
                "The following is a GitHub issue. It should clearly describe what is the problem, any proposed solutions to fix the problem and maybe also one or several next steps to fix it. A good issue description includes relevant context, is easy to understand, concise, and provides enough detail for others to address the problem" \
                "Please rate the clarity and completeness of the following GitHub issue description on a scale from 0 to 9, where 0 is extremely unclear and incomplete, and 9 is extremely clear and complete." \
                "Only provide a single number as your response." \
                "" \
                   "ISSUE TITLE: $ISSUE_TITLE" \
                "" \
                "ISSUE DESCRIPTION:" \
                "$ISSUE_DESCRIPTION")

                echo "PROMPT: $PROMPT"
                echo "cp 2409160805"


                # -------------------- SEND PROMPT TO LLM. GET BACK MESSAGE (REPEATING CODE) --------------------
                #  # Create the payload using jq to ensure valid JSON
                #   PAYLOAD=$(jq -n --arg model "gpt-4o" --arg content "$PROMPT" --argjson stream false --arg max_tokens 500 '{
                #     model: $model,
                #     messages: [
                #       {
                #         role: "user",
                #         content: $content
                #       }
                #     ],
                #     stream: $stream,
                #     max_tokens: ($max_tokens | tonumber)
                #   }')

                #   echo "PAYLOAD: $PAYLOAD"
                #   echo "cp 2409160822"

                #   # Validate the JSON payload
                #   echo "$PAYLOAD" | jq . > /dev/null
                #   if [ $? -ne 0 ]; then
                #     echo "Invalid JSON payload"
                #     exit 1
                #   fi
                #   echo "cp 2409160823"

                #   # Call your API with the issue description
                #   API_RESPONSE=$(curl -X POST -H "Content-Type: application/json" -H "User-Agent: GHAction/Issue-Checker" -H "api-key: ${{ secrets.ZOO_API_KEY }}" -d "$PAYLOAD" https://llm.reasoning.innovation.kognitwin.com/proxy/chat/completions)
                #   echo "API_RESPONSE: $API_RESPONSE"
                #   echo "cp 2409160824"

                #   # Parse the API response to extract the message
                #   MESSAGE=$(printf '%s' "$API_RESPONSE" | jq -r '.choices[0].message.content')
                MESSAGE="the rating of__ the text was :{3}:4 1 _" #<-- OPS!! Slett!! 
                echo "MESSAGE: $MESSAGE"
                echo "cp 2409160801" 
                # ____________________ SEND PROMPT TO LLM. GET BACK MESSAGE (REPEATING CODE) ____________________  

                # Extract rating number from the response
                RATING_NUMBER=$(echo "$MESSAGE" | grep -oE '[0-9]+' | head -n 1)
                echo "RATING_NUMBER: $RATING_NUMBER"
                echo "cp 2409160800"  

                # Ensure RATING_NUMBER is a valid number
                if ! [[ "$RATING_NUMBER" =~ ^[0-9]+$ ]]; then
                  echo "cp 2409160810"  
                  echo "Invalid rating number received: $RATING_NUMBER"
                  exit 1
                fi
                echo "cp 2409160811"

                echo "RATING_NUMBER=$RATING_NUMBER" >> $GITHUB_ENV

            - name: Comment on Issue if Rating is Low
              run: |

                # Set the threshold value
                THRESHOLD_VALUE=4

                echo "RATING_NUMBER: $RATING_NUMBER"
                echo "cp 240915212119"

                # Check if RATING_NUMBER is less than THRESHOLD_VALUE
                if [ "$RATING_NUMBER" -lt "$THRESHOLD_VALUE" ]; then
                  # Define the prompt using printf
                  PROMPT=$(printf '%s\n' \
                  "Please provide a concise and short bulletpoint list of things that can be improved about the following issue description." \
                  "Focus on clarity, how the proposed change can provide value, and if the proposed change considers its surrounding context." \
                  "" \
                  "Remember what a good issue for value-driven development looks like." \
                  "Think hard about it. Make sure you don't point out things that are already clear or that are not relevant to the issue." \
                  "At the end of the bulletpoint list, propose an alternate description based on your interpretation of the issue which adheres to your recommendations. " \
                  "Your response must be formated with markdown, and have the bulletpoint list in a collapsed section wrapped in a details tag." \
                  "The summary tag should summarize in one sentence the most important suggestion you have." \
                  "The alternate description should also be in a collapsed section wrapped in a details tag, but with the issue title in the summary tag." \
                  "If you are able to detect any relationships in the original issue description of any reasonable complexity, try to create a mermaid diagram to illustrate it and place it at the end." \
                  "" \
                  "ISSUE TITLE: $ISSUE_TITLE" \
                  "" \
                  "ISSUE DESCRIPTION:" \
                  "$ISSUE_DESCRIPTION")

                  echo "cp 2409160834"
                  echo "PROMPT: $PROMPT"
                  echo "cp 2409160835"
                  
                  # -------------------- SEND PROMPT TO LLM. GET BACK MESSAGE (REPEATING CODE) --------------------
                #  # Create the payload using jq to ensure valid JSON
                #   PAYLOAD=$(jq -n --arg model "gpt-4o" --arg content "$PROMPT" --argjson stream false --arg max_tokens 500 '{
                #     model: $model,
                #     messages: [
                #       {
                #         role: "user",
                #         content: $content
                #       }
                #     ],
                #     stream: $stream,
                #     max_tokens: ($max_tokens | tonumber)
                #   }')

                #   echo "PAYLOAD: $PAYLOAD"
                #   echo "cp 2409160822"

                #   # Validate the JSON payload
                #   echo "$PAYLOAD" | jq . > /dev/null
                #   if [ $? -ne 0 ]; then
                #     echo "Invalid JSON payload"
                #     exit 1
                #   fi
                #   echo "cp 2409160823"

                #   # Call your API with the issue description
                #   API_RESPONSE=$(curl -X POST -H "Content-Type: application/json" -H "User-Agent: GHAction/Issue-Checker" -H "api-key: ${{ secrets.ZOO_API_KEY }}" -d "$PAYLOAD" https://llm.reasoning.innovation.kognitwin.com/proxy/chat/completions)
                #   echo "API_RESPONSE: $API_RESPONSE"
                #   echo "cp 2409160824"

                #   # Parse the API response to extract the message
                #   MESSAGE=$(printf '%s' "$API_RESPONSE" | jq -r '.choices[0].message.content')
                  MESSAGE="Given rating was  $RATING_NUMBER" #<-- OPS!! Slett!! 
                  echo "MESSAGE: $MESSAGE"
                  echo "cp 2409160801" 
                  # ____________________ SEND PROMPT TO LLM. GET BACK MESSAGE (REPEATING CODE) ____________________  

                  # Write the message as a comment on the issue
                  gh issue --repo ${{ github.repository }} comment ${{ github.event.issue.number }} -b "$MESSAGE"
                else
                  echo "Rating ($RATING_NUMBER) is greater than or equal to threshold ($THRESHOLD_VALUE). No action needed."
                fi


              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
